CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Documents" (
    "DocumentId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Description" text NULL,
    "FileExtension" text NOT NULL,
    "FileSizeInBytes" bigint NOT NULL,
    "FilePath" text NOT NULL,
    "DateUploaded" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Documents" PRIMARY KEY ("DocumentId")
);

CREATE TABLE "Grants" (
    "GrantId" uuid NOT NULL,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "Amount" integer NOT NULL,
    "Criteria" text NOT NULL,
    "Deadline" timestamp with time zone NOT NULL,
    "DateCreated" timestamp with time zone NOT NULL,
    "DateModified" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Grants" PRIMARY KEY ("GrantId")
);

CREATE TABLE "Notifications" (
    "NotificationId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "Type" text NULL,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("NotificationId")
);

CREATE TABLE "Tasks" (
    "TaskId" integer GENERATED BY DEFAULT AS IDENTITY,
    "TaskName" text NOT NULL,
    "Description" text NOT NULL,
    "TaskStatus" text NOT NULL,
    "AssignedTo" text NOT NULL,
    "AssignedFrom" text NOT NULL,
    CONSTRAINT "PK_Tasks" PRIMARY KEY ("TaskId")
);

CREATE TABLE "Applicants" (
    "ApplicantId" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "Title" text NOT NULL,
    "Department" text NOT NULL,
    "Email" text NOT NULL,
    "PhoneNumber" text NOT NULL,
    "Status" text NOT NULL,
    "IsStaffMember" boolean NOT NULL,
    "DocumentId" integer NOT NULL,
    CONSTRAINT "PK_Applicants" PRIMARY KEY ("ApplicantId"),
    CONSTRAINT "FK_Applicants_Documents_DocumentId" FOREIGN KEY ("DocumentId") REFERENCES "Documents" ("DocumentId") ON DELETE CASCADE
);

CREATE TABLE "Awardees" (
    "AwardeeId" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "PhoneNumber" text NOT NULL,
    "Email" text NOT NULL,
    "AreaOfSpecialization" text NOT NULL,
    "Amount" integer NOT NULL,
    "DocumentId" integer NOT NULL,
    CONSTRAINT "PK_Awardees" PRIMARY KEY ("AwardeeId"),
    CONSTRAINT "FK_Awardees_Documents_DocumentId" FOREIGN KEY ("DocumentId") REFERENCES "Documents" ("DocumentId") ON DELETE CASCADE
);

CREATE INDEX "IX_Applicants_DocumentId" ON "Applicants" ("DocumentId");

CREATE INDEX "IX_Awardees_DocumentId" ON "Awardees" ("DocumentId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251110152605_Initial Migration', '7.0.18');

COMMIT;

